/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CoCurricularRouteImport } from './routes/co-curricular'
import { Route as CollegeRouteImport } from './routes/college'
import { Route as TenderlyRouteImport } from './routes/tenderly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoCurricularRoute = CoCurricularRouteImport.update({
  id: '/co-curricular',
  path: '/co-curricular',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRoute = CollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderlyRoute = TenderlyRouteImport.update({
  id: '/tenderly',
  path: '/tenderly',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/co-curricular': typeof CoCurricularRoute
  '/college': typeof CollegeRoute
  '/tenderly': typeof TenderlyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/co-curricular': typeof CoCurricularRoute
  '/college': typeof CollegeRoute
  '/tenderly': typeof TenderlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/co-curricular': typeof CoCurricularRoute
  '/college': typeof CollegeRoute
  '/tenderly': typeof TenderlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/co-curricular' | '/college' | '/tenderly'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/co-curricular' | '/college' | '/tenderly'
  id: '__root__' | '/' | '/about' | '/co-curricular' | '/college' | '/tenderly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoCurricularRoute: typeof CoCurricularRoute
  CollegeRoute: typeof CollegeRoute
  TenderlyRoute: typeof TenderlyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co-curricular': {
      id: '/co-curricular'
      path: '/co-curricular'
      fullPath: '/co-curricular'
      preLoaderRoute: typeof CoCurricularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenderly': {
      id: '/tenderly'
      path: '/tenderly'
      fullPath: '/tenderly'
      preLoaderRoute: typeof TenderlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoCurricularRoute: CoCurricularRoute,
  CollegeRoute: CollegeRoute,
  TenderlyRoute: TenderlyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
